version: '3'
services:
  atp-db:
    image: postgres:13-alpine
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: atp-db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data/csv-files:/csv-files
volumes:
  postgres-data:
